FROM python:slim

RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN python -m pip install gevent
RUN pip install pymysql

COPY . /app
WORKDIR /app

CMD ["dockerize", "-wait", "tcp://mariadb:3306"] 
CMD ["python", "-u", "./db-setup.py"]