FROM python:slim

COPY . /app
WORKDIR /app

RUN pip install steam
RUN pip install redis
RUN pip install pymysql
RUN pip install --upgrade sentry-sdk==0.3.5

CMD ["python", "-u", "./packages-updater.py"]