FROM python:slim

RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY . /app
WORKDIR /app

RUN pip install git+https://github.com/ValvePython/steam
RUN pip install redis
RUN pip install pymysql
RUN pip install --upgrade sentry-sdk==0.3.5

CMD ["dockerize", "-wait", "tcp://mariadb:3306"] 
CMD ["python", "-u", "./packages-updater.py"]